version: '3.8'

services:
  dl_database:
    container_name: dl_database
    image: postgres:12.13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - dl_database_volume:/var/lib/postgresql/data
    networks:
      - dl_default_network

  dl_app:
    container_name: dl_nodejsdock
    build:
      context: ./Docker
      dockerfile: Dockerfile-app
    env_file: ./.env
    ports:
      - ${HTTP_PORT}:3001
    volumes:
      - .:/home/dl_app
    networks:
      - dl_default_network

  dl_queue:
    container_name: dl_queue
    build:
      context: ./Docker
      dockerfile: Dockerfile-queue
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  dl_database_volume:

networks:
  dl_default_network:
