version: '3.9'

services:
  contract_app_database:
    container_name: contract_app_database
    image: postgres:12.13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - contract_app_database_volume:/var/lib/postgresql/data
    networks:
      - contract_app_default_network

  contract_app_app:
    depends_on:
      - contract_app_database
    container_name: contract_app_nodejsdock
    build:
      context: ./Docker
      dockerfile: Dockerfile-app
    env_file: ./.env
    ports:
      - ${HTTP_PORT}:3001
    volumes:
      - .:/home/contract_app_app
    networks:
      - contract_app_default_network

  contract_app_queue:
    container_name: contract_app_queue
    build:
      context: ./Docker
      dockerfile: Dockerfile-queue
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  contract_app_database_volume:

networks:
  contract_app_default_network:
